// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/chat/ai-response.ts";
import * as $$$$$$$$$1 from "./actions/chat/stream-ai-response.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/avaliableAssistants.ts";
import * as $$$$$$0 from "./sections/Chat.tsx";
import * as $$$$$$1 from "./sections/Component.tsx";
import * as $$$$$$2 from "./sections/Home.tsx";
import * as $$$$$$3 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/avaliableAssistants.ts": $$$0,
  },
  "sections": {
    "site/sections/Chat.tsx": $$$$$$0,
    "site/sections/Component.tsx": $$$$$$1,
    "site/sections/Home.tsx": $$$$$$2,
    "site/sections/Theme/Theme.tsx": $$$$$$3,
  },
  "actions": {
    "site/actions/chat/ai-response.ts": $$$$$$$$$0,
    "site/actions/chat/stream-ai-response.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
